name: Run Serv00 Crawler

on:
  push:
    branches:
      - main # 或者你想要触发的 branch
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 根据你的python版本修改

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run crawler
        env:
          EMAIL_DOMAIN: ${{ secrets.EMAIL_DOMAIN || 'openai.myfw.us' }}
          NUM_EMAILS: ${{ secrets.NUM_EMAILS || '10' }}
        run: python3 main.py