name: Automated Signup

on:
  
  workflow_dispatch:  # 允许手动触发

jobs:
  signup:
    runs-on: ubuntu-latest
    
    env:
      PROXY_LIST: ${{ secrets.SOCKS }}
      TARGET_EMAIL: ${{ secrets.EMAIL_DOMAIN }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 ddddocr
          
      - name: Create proxy list file
        run: echo "$PROXY_LIST" > proxies.list
        
      - name: Run signup script
        run: |
          python index.js "$TARGET_EMAIL"
        
      - name: Clean up
        if: always()
        run: rm -f proxies.list
