name: Run Serv00 Crawler

on:
  push:
    branches:
      - main # 或者你想要触发的 branch
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 根据你的python版本修改

      - name: Install dependencies
        run: pip3 install -r requirements.txt


      - name: Set up WARP with client
        uses: fscarmen/warp-on-actions@v1.3
        with:
          stack: dual
          mode: wireguard
          
          
      - name: Run crawler
        env:
          EMAIL_DOMAIN: ${{ secrets.EMAIL_DOMAIN || '' }}
          NUM_EMAILS: ${{ secrets.NUM_EMAILS || '20' }}
          MAX_CAPTCHA_RETRIES: ${{ secrets.MAX_CAPTCHA_RETRIES || '5' }}
          MAX_EMAIL_RETRIES: ${{ secrets.MAX_EMAIL_RETRIES || '20' }}
          TG: ${{ secrets.TG || '' }}
          SOCKS: ${{ secrets.SOCKS || '' }}
        run: python3 main.py